App\Entity\UserAccount:
  attributes:
    username:
      groups: ['user_account:read', 'user_account:write']
    email:
      groups: ['user_account:read', 'user_account:write']
    password:
      groups: ['user_account:write']
    roles:
      groups: ['user_account:read']
    isActive:
      groups: ['user_account:read']
