app_login:
  path: /login
  methods: [post]
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  methods: [post]
  controller: App\Controller\SecurityController::logout
