App\Entity\ExampleResourceEntity:
  properties:
    title:
      - NotBlank: ~
    description:
      - NotBlank: ~
    owner:
      - DisableAutoMapping: ~ #disabled because default value is set with doctrine entity listener on prePersist event
      - App\Validator\IsValidOwner: ~
  attributes:
    title:
      groups: ['example_resource_entity:read', 'example_resource_entity:write', 'user_account:read']
    description:
      groups: ['example_resource_entity:read', 'example_resource_entity:write']
    owner:
      groups: ['example_resource_entity:read', 'example_resource_entity:collection:post']

resources:
  App\Entity\ExampleResourceEntity:
    description: 'Object representing Example Filtered resource'
    shortName: 'example_resource_entity'
    attributes:
      pagination_items_per_page: 20
      formats:
        0: 'jsonld'
        1: 'json'
        2: 'html'
        csv: ['text/csv']
      security: 'is_granted("ROLE_USER")'
    itemOperations:
      get: ~
      patch:
        security: 'is_granted("EXAMPLE_RESOURCE_ENTITY_EDIT", object)'
        security_message: 'Only the creator can edit exampleResourceEntities.'
      put:
        security: 'is_granted("EXAMPLE_RESOURCE_ENTITY_EDIT", object)'
        security_message: 'Only the creator can edit exampleResourceEntities.'
      delete:
        security: 'is_granted("ROLE_ADMIN")'
    collectionOperations:
      get: ~
      post: ~
    properties:
      owner:
        readableLink: false
        writableLink: false
