App\Entity\UserAccount:
  properties:
    username:
      - NotBlank: ~
    email:
      - NotBlank: ~
      - Email: ~
    password:
      - NotBlank: ~
  attributes:
    username:
      groups: ['user_account:read', 'user_account:write', 'example_resource_entity:read']
    email:
      groups: ['user_account:read', 'user_account:write']
    password:
      groups: ['user_account:write']
    roles:
      groups: ['user_account:read']
    isActive:
      groups: ['user_account:read']
    exampleResourceEntities:
      groups: ['user_account:read' ]

resources:
  App\Entity\UserAccount:
    description: 'Object representing api users'
    attributes:
      normalization_context:
        groups: [ 'user_account:read' ]
      denormalization_context:
        groups: [ 'user_account:write' ]
    itemOperations: ['get', 'patch']
    properties:
      exampleResourceEntities:
        subresource:
          resourceClass: App\Entity\ExampleResourceEntity
          collection: false
